[project]
name = "clara"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aryan-202", email = "aryanvishwakarma275@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "google-api-python-client>=2.200.0",
    "google-auth>=2.57.0",
    "google-auth-httplib2>=0.4.2",
    "google-auth-oauthlib>=1.4.1",
    "python-dotenv>=1.2.3",
    "setuptools>=84.0.0",
]

[project.scripts]
clara = "clara.main:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["clara*"]
exclude = ["tests*", "docs*", "scripts*", "release*"]
