[project]
name = "clara-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aryan-202", email = "aryanvishwakarma275@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
clara-core = "clara_core:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
