[pytest]
minversion = 7.0
testpaths = tests
pythonpath = .
python_files = test_*.py
python_classes = Test* Test_* *Test
python_functions = test_*
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
addopts = -v --strict-markers
markers =
    asyncio: marks tests as asyncio
    slow: marks tests as slow
