name: SLSA generic generator
on:
  release:
    types: [created]

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.digests }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create dummy artifact
        run: |
          mkdir -p dist
          echo "hello world" > dist/artifact.txt

      - name: Generate hashes
        id: hash
        run: |
          echo "hashes=$(sha256sum dist/artifact.txt | base64 -w0)" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: dist/

  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0
    with:
      base64-subjects: "${{ needs.build.outputs.digests }}"
      upload-assets: true
